<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nis2Dettaglio;

class Nis2DettaglioSeeder extends Seeder
{
    public function run(): void
    {
        $csv = <<<CSV
"ID Voce","Voce","ID Sottovoce","Sottovoce","Adempimento da fare","Documentazione da produrre"
"1","Governance e Responsabilità","1.1","Impegno e Supervisione del CdA","Gli organi di gestione (CdA, Amministratore Unico) devono approvare le policy di cybersecurity, supervisionarne l'attuazione e sono ritenuti direttamente responsabili in caso di non conformità.","Verbali del CdA/organo di gestione che approvano e riesaminano la strategia e le policy di sicurezza"
"1","Governance e Responsabilità","1.1","Impegno e Supervisione del CdA","Gli organi di gestione (CdA, Amministratore Unico) devono approvare le policy di cybersecurity, supervisionarne l'attuazione e sono ritenuti direttamente responsabili in caso di non conformità.","Matrice di assegnazione responsabilità (RACI Matrix)."
"1","Governance e Responsabilità","1.2","Formazione del Management","Gli organi di gestione devono seguire una formazione specifica e regolare per comprendere e valutare i rischi e le pratiche di cybersecurity.","Attestati di partecipazione alla formazione"
"1","Governance e Responsabilità","1.2","Formazione del Management","Gli organi di gestione devono seguire una formazione specifica e regolare per comprendere e valutare i rischi e le pratiche di cybersecurity.","Programma del corso di formazione seguito dal management."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.1","Policy di Analisi del Rischio e Sicurezza dei Sistemi","Adottare e mantenere aggiornate policy per l'analisi dei rischi e per la sicurezza dei sistemi informativi, volte a proteggere le reti e le informazioni.","Policy di Sicurezza delle Informazioni (PSI)"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.1","Policy di Analisi del Rischio e Sicurezza dei Sistemi","Adottare e mantenere aggiornate policy per l'analisi dei rischi e per la sicurezza dei sistemi informativi, volte a proteggere le reti e le informazioni.","Policy di Analisi del Rischio"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.1","Policy di Analisi del Rischio e Sicurezza dei Sistemi","Adottare e mantenere aggiornate policy per l'analisi dei rischi e per la sicurezza dei sistemi informativi, volte a proteggere le reti e le informazioni.","Documento di Valutazione dei Rischi (Risk Assessment)."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.2","Gestione degli Incidenti","Stabilire e attuare procedure per prevenire, rilevare, analizzare, gestire e rispondere agli incidenti di sicurezza per minimizzarne l'impatto.","Piano di Gestione degli Incidenti (Incident Response Plan)"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.2","Gestione degli Incidenti","Stabilire e attuare procedure per prevenire, rilevare, analizzare, gestire e rispondere agli incidenti di sicurezza per minimizzarne l'impatto.","Procedure operative di classificazione e risposta"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.2","Gestione degli Incidenti","Stabilire e attuare procedure per prevenire, rilevare, analizzare, gestire e rispondere agli incidenti di sicurezza per minimizzarne l'impatto.","Registri e report degli incidenti."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.3","Continuità Operativa e Gestione delle Crisi","Garantire la continuità operativa durante e dopo incidenti gravi. Include la gestione dei backup, il disaster recovery e la gestione delle crisi.","Piano di Continuità Operativa (Business Continuity Plan)"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.3","Continuità Operativa e Gestione delle Crisi","Garantire la continuità operativa durante e dopo incidenti gravi. Include la gestione dei backup, il disaster recovery e la gestione delle crisi.","Piano di Disaster Recovery"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.3","Continuità Operativa e Gestione delle Crisi","Garantire la continuità operativa durante e dopo incidenti gravi. Include la gestione dei backup, il disaster recovery e la gestione delle crisi.","Policy e procedure di backup e ripristino"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.3","Continuità Operativa e Gestione delle Crisi","Garantire la continuità operativa durante e dopo incidenti gravi. Include la gestione dei backup, il disaster recovery e la gestione delle crisi.","Report dei test di ripristino."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.4","Sicurezza della Catena di Approvvigionamento","Identificare e gestire i rischi legati ai fornitori di servizi ICT e alla catena di approvvigionamento. Valutare e verificare la postura di sicurezza dei fornitori.","Policy per la sicurezza della supply chain"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.4","Sicurezza della Catena di Approvvigionamento","Identificare e gestire i rischi legati ai fornitori di servizi ICT e alla catena di approvvigionamento. Valutare e verificare la postura di sicurezza dei fornitori.","Clausole contrattuali di sicurezza per i fornitori"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.4","Sicurezza della Catena di Approvvigionamento","Identificare e gestire i rischi legati ai fornitori di servizi ICT e alla catena di approvvigionamento. Valutare e verificare la postura di sicurezza dei fornitori.","Report di audit e valutazione sui fornitori critici."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.5","Sicurezza nell'Acquisizione, Sviluppo e Manutenzione dei Sistemi","Integrare la sicurezza nel ciclo di vita dei sistemi informativi (Secure by Design/Default). Gestire e divulgare le vulnerabilità identificate.","Policy per lo sviluppo sicuro (Secure SDLC)"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.5","Sicurezza nell'Acquisizione, Sviluppo e Manutenzione dei Sistemi","Integrare la sicurezza nel ciclo di vita dei sistemi informativi (Secure by Design/Default). Gestire e divulgare le vulnerabilità identificate.","Procedure di Vulnerability Management"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.5","Sicurezza nell'Acquisizione, Sviluppo e Manutenzione dei Sistemi","Integrare la sicurezza nel ciclo di vita dei sistemi informativi (Secure by Design/Default). Gestire e divulgare le vulnerabilità identificate.","Report di scansione delle vulnerabilità"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.5","Sicurezza nell'Acquisizione, Sviluppo e Manutenzione dei Sistemi","Integrare la sicurezza nel ciclo di vita dei sistemi informativi (Secure by Design/Default). Gestire e divulgare le vulnerabilità identificate.","Procedure di patch management."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.6","Valutazione dell'Efficacia delle Misure","Adottare policy e procedure per testare e valutare periodicamente l'efficacia delle misure di gestione del rischio implementate (es. audit, test).","Policy di audit e testing di sicurezza"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.6","Valutazione dell'Efficacia delle Misure","Adottare policy e procedure per testare e valutare periodicamente l'efficacia delle misure di gestione del rischio implementate (es. audit, test).","Report di Penetration Test"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.6","Valutazione dell'Efficacia delle Misure","Adottare policy e procedure per testare e valutare periodicamente l'efficacia delle misure di gestione del rischio implementate (es. audit, test).","Report di Vulnerability Assessment"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.6","Valutazione dell'Efficacia delle Misure","Adottare policy e procedure per testare e valutare periodicamente l'efficacia delle misure di gestione del rischio implementate (es. audit, test).","Piani di rimedio delle non conformità."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.7","Igiene Informatica e Formazione","Promuovere pratiche di base di 'igiene informatica' (cyber hygiene) e fornire formazione periodica sulla cybersecurity a tutto il personale.","Policy di Cyber Hygiene"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.7","Igiene Informatica e Formazione","Promuovere pratiche di base di 'igiene informatica' (cyber hygiene) e fornire formazione periodica sulla cybersecurity a tutto il personale.","Programma di formazione e awareness"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.7","Igiene Informatica e Formazione","Promuovere pratiche di base di 'igiene informatica' (cyber hygiene) e fornire formazione periodica sulla cybersecurity a tutto il personale.","Registri di partecipazione e materiali didattici"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.7","Igiene Informatica e Formazione","Promuovere pratiche di base di 'igiene informatica' (cyber hygiene) e fornire formazione periodica sulla cybersecurity a tutto il personale.","Report delle campagne di phishing simulato."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.8","Uso della Crittografia e Cifratura","Definire e applicare policy sull'uso della crittografia (dati a riposo e in transito) e della cifratura, ove appropriato, in base alla valutazione del rischio.","Policy sull'uso della crittografia"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.8","Uso della Crittografia e Cifratura","Definire e applicare policy sull'uso della crittografia (dati a riposo e in transito) e della cifratura, ove appropriato, in base alla valutazione del rischio.","Inventario degli algoritmi e delle chiavi crittografiche"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.8","Uso della Crittografia e Cifratura","Definire e applicare policy sull'uso della crittografia (dati a riposo e in transito) e della cifratura, ove appropriato, in base alla valutazione del rischio.","Procedure di gestione delle chiavi."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.9","Sicurezza delle Risorse Umane e Controllo Accessi","Implementare policy di sicurezza per le risorse umane (onboarding, offboarding) e policy rigorose per il controllo degli accessi basate sui principi di 'least privilege' e 'need-to-know'.","Policy per la sicurezza delle Risorse Umane"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.9","Sicurezza delle Risorse Umane e Controllo Accessi","Implementare policy di sicurezza per le risorse umane (onboarding, offboarding) e policy rigorose per il controllo degli accessi basate sui principi di 'least privilege' e 'need-to-know'.","Policy per il Controllo degli Accessi (Access Control Policy)"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.9","Sicurezza delle Risorse Umane e Controllo Accessi","Implementare policy di sicurezza per le risorse umane (onboarding, offboarding) e policy rigorose per il controllo degli accessi basate sui principi di 'least privilege' e 'need-to-know'.","Procedure per la gestione delle identità e degli accessi (IAM)."
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.10","Autenticazione a Più Fattori (MFA)","Utilizzare soluzioni di autenticazione a più fattori (MFA) o di autenticazione continua per l'accesso a sistemi, dati e servizi critici.","Policy sull'autenticazione"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.10","Autenticazione a Più Fattori (MFA)","Utilizzare soluzioni di autenticazione a più fattori (MFA) o di autenticazione continua per l'accesso a sistemi, dati e servizi critici.","Documentazione tecnica dell'implementazione della MFA"
"2","Misure di Gestione del Rischio (CRM) - Art. 21","2.10","Autenticazione a Più Fattori (MFA)","Utilizzare soluzioni di autenticazione a più fattori (MFA) o di autenticazione continua per l'accesso a sistemi, dati e servizi critici.","Log di accesso che evidenziano l'uso della MFA."
"3","Obblighi di Segnalazione","3.1","Segnalazione Precoce (Early Warning)","Inviare una segnalazione precoce al CSIRT competente e/o all'autorità nazionale entro 24 ore dalla conoscenza di un incidente significativo.","Copia della notifica di pre-allarme inviata."
"3","Obblighi di Segnalazione","3.2","Notifica dell'Incidente","Inviare una notifica completa dell'incidente entro 72 ore, aggiornando la segnalazione precoce e fornendo una prima valutazione dell'impatto.","Copia della notifica completa inviata."
"3","Obblighi di Segnalazione","3.3","Relazione Intermedia e Finale","Fornire relazioni intermedie su richiesta e una relazione finale entro un mese dalla risoluzione dell'incidente, descrivendo le cause, le misure di mitigazione e l'impatto.","Copia della relazione finale inviata al CSIRT/autorità."
"3","Obblighi di Segnalazione","3.4","Comunicazione al Pubblico","In alcuni casi, comunicare l'incidente ai destinatari dei propri servizi che potrebbero essere impattati dalla minaccia.","Procedure di comunicazione pubblica"
"3","Obblighi di Segnalazione","3.4","Comunicazione al Pubblico","In alcuni casi, comunicare l'incidente ai destinatari dei propri servizi che potrebbero essere impattati dalla minaccia.","Copia delle comunicazioni inviate."
"10","Governance","10.1","Impegno dell'organo di gestione","L'organo di gestione (CdA, AU) deve formalmente approvare la strategia di cybersecurity e le relative policy. Deve supervisionare attivamente l'implementazione delle misure di sicurezza e allocare un budget adeguato. La responsabilità per la non conformità ricade direttamente su di loro.","Delibera del CdA o verbale firmato che approva la Politica di Sicurezza delle Informazioni e il piano di gestione dei rischi"
"10","Governance","10.1","Impegno dell'organo di gestione","L'organo di gestione (CdA, AU) deve formalmente approvare la strategia di cybersecurity e le relative policy. Deve supervisionare attivamente l'implementazione delle misure di sicurezza e allocare un budget adeguato. La responsabilità per la non conformità ricade direttamente su di loro.","Documento di budget che evidenzia gli stanziamenti per la cybersecurity"
"10","Governance","10.1","Impegno dell'organo di gestione","L'organo di gestione (CdA, AU) deve formalmente approvare la strategia di cybersecurity e le relative policy. Deve supervisionare attivamente l'implementazione delle misure di sicurezza e allocare un budget adeguato. La responsabilità per la non conformità ricade direttamente su di loro.","Matrice delle responsabilità (es. RACI) approvata."
"11","Governance","11.2","Gestione e formazione dei dipendenti","Implementare un programma di formazione obbligatorio e continuo sulla consapevolezza dei rischi informatici per tutto il personale. Definire policy chiare sulla sicurezza delle risorse umane, inclusi i processi di assunzione (background check, se applicabile) e cessazione del rapporto (revoca accessi).","Programma del piano di formazione e awareness"
"11","Governance","11.2","Gestione e formazione dei dipendenti","Implementare un programma di formazione obbligatorio e continuo sulla consapevolezza dei rischi informatici per tutto il personale. Definire policy chiare sulla sicurezza delle risorse umane, inclusi i processi di assunzione (background check, se applicabile) e cessazione del rapporto (revoca accessi).","Registro delle partecipazioni ai corsi con firme o log digitali"
"11","Governance","11.2","Gestione e formazione dei dipendenti","Implementare un programma di formazione obbligatorio e continuo sulla consapevolezza dei rischi informatici per tutto il personale. Definire policy chiare sulla sicurezza delle risorse umane, inclusi i processi di assunzione (background check, se applicabile) e cessazione del rapporto (revoca accessi).","Policy di sicurezza delle risorse umane (HR Security Policy)"
"11","Governance","11.2","Gestione e formazione dei dipendenti","Implementare un programma di formazione obbligatorio e continuo sulla consapevolezza dei rischi informatici per tutto il personale. Definire policy chiare sulla sicurezza delle risorse umane, inclusi i processi di assunzione (background check, se applicabile) e cessazione del rapporto (revoca accessi).","Checklist per l'onboarding e l'offboarding del personale."
"20","Gestione del Rischio di Cibersicurezza","20.3","Approccio al Rischio","Adottare un approccio 'all-hazards' (che consideri ogni tipo di minaccia), basato sul rischio. Le misure di sicurezza devono essere il risultato di una valutazione del rischio che identifichi minacce, vulnerabilità e impatti potenziali sui servizi essenziali o importanti forniti.","Documento di metodologia dell'analisi del rischio (Risk Assessment Methodology)"
"20","Gestione del Rischio di Cibersicurezza","20.3","Approccio al Rischio","Adottare un approccio 'all-hazards' (che consideri ogni tipo di minaccia), basato sul rischio. Le misure di sicurezza devono essere il risultato di una valutazione del rischio che identifichi minacce, vulnerabilità e impatti potenziali sui servizi essenziali o importanti forniti.","Policy di gestione del rischio che descrive l'approccio complessivo dell'organizzazione."
"21","Gestione del Rischio di Cibersicurezza","21.4","Standard Europei e costi di implementazione","Tenere conto delle norme europee e internazionali (es. serie ISO/IEC 27001, framework NIST) come riferimento per l'implementazione delle misure. Valutare e documentare i costi di implementazione in relazione ai rischi mitigati per garantirne l'adeguatezza.","Documento di 'Statement of Applicability' (SoA) o Gap Analysis rispetto a uno standard di riferimento (es. ISO 27001)"
"21","Gestione del Rischio di Cibersicurezza","21.4","Standard Europei e costi di implementazione","Tenere conto delle norme europee e internazionali (es. serie ISO/IEC 27001, framework NIST) come riferimento per l'implementazione delle misure. Valutare e documentare i costi di implementazione in relazione ai rischi mitigati per garantirne l'adeguatezza.","Analisi costi-benefici per le misure di sicurezza implementate"
"21","Gestione del Rischio di Cibersicurezza","21.4","Standard Europei e costi di implementazione","Tenere conto delle norme europee e internazionali (es. serie ISO/IEC 27001, framework NIST) come riferimento per l'implementazione delle misure. Valutare e documentare i costi di implementazione in relazione ai rischi mitigati per garantirne l'adeguatezza.","Preventivi e fatture relative a soluzioni e servizi di cybersecurity."
"22","Gestione del Rischio di Cibersicurezza","22.5","Proporzionalità delle misure","Le misure tecniche, operative e organizzative devono essere proporzionate alla dimensione dell'entità, all'esposizione al rischio, alla probabilità che si verifichi un incidente e alla sua potenziale gravità, inclusi gli impatti economici e sociali.","Il Documento di Valutazione del Rischio (Risk Assessment) deve contenere la giustificazione della scelta (o non scelta) delle contromisure in base al livello di rischio calcolato e ai criteri di proporzionalità definiti."
"23","Gestione del Rischio di Cibersicurezza","23.6","Analisi del Rischio e Sicurezza del sistema informatico","Eseguire e documentare un'analisi del rischio completa e periodica su tutti gli asset che supportano i servizi forniti. Implementare le misure di sicurezza tecniche (firewall, antivirus, crittografia, ecc.) e organizzative (procedure, controlli) derivanti dall'analisi.","Documento di Valutazione dei Rischi completo e aggiornato"
"23","Gestione del Rischio di Cibersicurezza","23.6","Analisi del Rischio e Sicurezza del sistema informatico","Eseguire e documentare un'analisi del rischio completa e periodica su tutti gli asset che supportano i servizi forniti. Implementare le misure di sicurezza tecniche (firewall, antivirus, crittografia, ecc.) e organizzative (procedure, controlli) derivanti dall'analisi.","Inventario degli asset (Asset Inventory)"
"23","Gestione del Rischio di Cibersicurezza","23.6","Analisi del Rischio e Sicurezza del sistema informatico","Eseguire e documentare un'analisi del rischio completa e periodica su tutti gli asset che supportano i servizi forniti. Implementare le misure di sicurezza tecniche (firewall, antivirus, crittografia, ecc.) e organizzative (procedure, controlli) derivanti dall'analisi.","Piano di Trattamento del Rischio (Risk Treatment Plan)"
CSV;
        $lines = explode("\n", $csv);
        $header = null;
        foreach ($lines as $i => $line) {
            if ($i == 0) continue; // skip header
            $row = str_getcsv($line);
            if (count($row) < 6) continue;
            Nis2Dettaglio::create([
                'id_voce' => $row[0],
                'voce' => $row[1],
                'id_sottovoce' => $row[2],
                'sottovoce' => $row[3],
                'adempimento' => $row[4],
                'documentazione' => $row[5],
            ]);
        }
    }
}
